# Generated by Django 5.0.1 on 2024-02-09 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_publication_users_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='users_like',
        ),
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
